version: '3'
services:
  asterisk-api:
    build: .
    # ports:
    #   - "666:5000"
    volumes:
      - .:/app
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    network_mode: host