version: '3'
services:
  asterisk-api:
    build: .
    ports:
      - "666:5000"
    volumes:
      - .:/app
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ulimits:
      nproc: 65535  # Увеличиваем лимит потоков (например, до 65535)
      nofile:
        soft: 20000 # Увеличиваем лимит открытых файловых дескрипторов
        hard: 40000
