version: '3'
services:
  web:
    build: .
    # ports:
    #   - "666:666"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://localhost:6379/0
    network_mode: host

  redis:
    image: "redis:alpine"
    network_mode: host
  celery:
    build: .
    command: celery -A server.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://localhost:6379/0
    network_mode: host